# This is the workflow for the CI/CD and release
#
name: Release

on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  lint-code:
    name: '▶️ ATOS-Actions'
    uses: ATOS-Actions/actions/.github/workflows/lint-code.yml@v1

  test:
    needs: [lint-code]
    uses: ./.github/workflows/test.yml

  release:
    name: '▶️ ATOS-Actionse'
    needs: [lint-code, test]
    uses: ATOS-Actions/actions/.github/workflows/release.yml@v1
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}
